### Api Link
@baseUrl = http://localhost:3000/api/v1
@email=User@gmail.com

###password
@password=1
###Authentication Token
@Auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxOUBnbSIsImlhdCI6MTY4Mjc4Nzg1MSwiZXhwIjoxNjgyNzkxNDUxfQ.QPeczM0X5VbF7m-qtKDQ0RG_XgOHQohRP1BiuozdEqY
### test

### Register New User
POST  {{baseUrl}}/register
Content-Type: application/json

{
"name": "name",
"email": "test19@gm",
"password": "{{password}}"


}
### Login New User
POST  {{baseUrl}}/login
Content-Type: application/json

{
"email": "test19@gm",
"password": "{{password}}"

}
### protectedAuth
GET  {{baseUrl}}/protect
Content-Type: application/json
Authorization: Bearer {{Auth_token}}






