### Api Link
@baseUrl = http://localhost:3000/api/v1
@email=User@gmail.com

###password
@password=1
###Authentication Token
@Auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxOUBnbSIsImlhdCI6MTY4Mjc5OTc3NX0.hiPCqvI04e28CvbGg_Yf7oVfaqBOX0B6OBdgw8xXFIw
### test

### Register New User
POST  {{baseUrl}}/register
Content-Type: application/json

{
"name": "name",
"email": "test19@gm3",
"password": "{{password}}"


}
### Login New User
POST  {{baseUrl}}/login
Content-Type: application/json

{
"email": "test19@gm",
"password": "{{password}}"

}

### Logout
GET  {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{Auth_token}}

### Insert New Records
POST  {{baseUrl}}/addProduct
Content-Type: application/json
Authorization: Bearer {{Auth_token}}

{
"name": "nyota",
"price":"45",
"description": "ghhhjgj"

}


### Get all Records
GET  {{baseUrl}}/getProducts
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

### Get a record by id (here you may pass id through link)
GET  {{baseUrl}}/getProductById/1
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

### Search Product By Name

GET  {{baseUrl}}/getProductByName/nyot
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}




### Update a record by id(here you may pass id through link)
PUT  {{baseUrl}}/updateProduct/1
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"name":"keb",
"description":"jeje",
"price":"34"


}


### Delete a record by id(here you may pass id through link)
DELETE {{baseUrl}}/deleteProduct/1
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}


### protectedAuth
GET  {{baseUrl}}/protect
Content-Type: application/json
Authorization: Bearer {{Auth_token}}






